In [24]:
from pymongo import MongoClient
import pandas as pd
from pandas.io.json import json_normalize

In [25]:
client = MongoClient('localhost', 27017)
db = client['companies']
collection = db.companies

In [30]:
companies = collection.find(
    {'$and':[
        {'$or':[
            {'category_code': 'web'},
            {'category_code': 'software'},
            {'category_code': 'games_video'},
            {'category_code': 'social'}]},
        {'$or':[
            {'number_of_employees': {'$lte': 50}},
            {'number_of_employees': {'$gte': 250}}]},
        {'offices.latitude': {'$ne': None}},
        {'offices.latitude': {'$ne': None}},
        {'founded_year': {'$gte': 2005}}, {'offices': { '$ne': []} }]},
    {'name' : 1, 'category_code' : 1, 'number_of_employees' : 1,
     'founded_year' : 1, 'offices.country_code': 1, 'offices.city': 1, 'offices.latitude' : 1, 'offices.longitude' : 1, '_id': 0})

print(companies)

<pymongo.cursor.Cursor object at 0x7fc05c8a7a20>

In [31]:
data = json_normalize(data = companies, record_path = 'offices', meta = ['name', 'category_code', 'number_of_employees', 'founded_year'])
data

,city,country_code,latitude,longitude,name,category_code,number_of_employees,founded_year
0,Seattle,USA,47.603122,-122.333253,Wetpaint,web,47,2005
1,New York,USA,40.723731,-73.996431,Wetpaint,web,47,2005
2,Pleasanton,USA,37.692934,-121.904945,Zoho,software,1600,2005
3,West Hollywood,USA,34.090368,-118.393064,Geni,web,18,2006
4,New York City,USA,40.757929,-73.985506,MeetMoi,social,15,2007
5,New York,USA,40.746497,-74.009447,Joost,games_video,0,2006
6,San Francisco,USA,37.776805,-122.416924,Twitter,social,1300,2006
7,Culver City,USA,34.017606,-118.487267,Mahalo,web,40,2007
8,San Francisco,USA,37.788482,-122.409173,Kyte,games_video,40,2006
9,Pleasanton,USA,37.697805,-121.907768,Jangl SMS,web,22,2005
10,Los Angeles,USA,34.051409,-118.254558,Stickam,games_video,35,2006
11,San Bruno,USA,37.627971,-122.426804,YouTube,games_video,0,2005
12,NYC,USA,40.801358,-74.337200,AdaptiveBlue,games_video,15,2007
13,San Francisco,USA,37.762541,-122.397224,Pownce,web,6,2007
14,None,USA,37.269175,-119.306607,CriticalMetrics,web,4,2007
15,San Francisco,USA,37.780716,-122.393913,CastTV,games_video,0,2006
16,Encino,USA,37.269175,-119.306607,SodaHead,web,25,2007
17,Agoura Hills,USA,34.155211,-118.756618,ClipBlast!,web,15,2005
18,Santa Clara,USA,37.380101,-121.940749,Spotplex,web,3,2007
19,Amsterdam,NLD,52.375595,4.908556,Fleck,web,3,2006
20,Amsterdam,NLD,52.374523,4.894862,Wakoopa,web,8,2007
21,Southampton,GBR,50.944460,-1.361085,Zamzar,web,2,2006
22,Sunnyvale,USA,37.369650,-122.024210,coRank,web,0,2007
23,San Francisco,USA,37.758113,-122.414689,Pageflakes,web,20,2006
24,Mill Valley,USA,37.900770,-122.511687,CrowdVine,web,10,2007
25,Seattle,USA,47.614653,-122.338793,TripHub,web,6,2005
26,San Francisco,USA,37.782103,-122.401116,Bebo,web,0,2005
27,Paris,FRA,48.866323,2.381514,WatZatSong,web,3,2006
28,Seattle,USA,47.618599,-122.358484,Newsvine,web,8,2005
29,Palo Alto,USA,37.437328,-122.159928,Terabitz,web,12,2006
...,...,...,...,...,...,...,...,...
1657,Monte Sereno,USA,37.241813,-121.986779,Asyus,web,7,2009
1658,Austin,USA,30.305809,-97.817760,LugIron Software,software,10,2009
1659,New York,USA,40.740804,-74.007170,ChallengePost,web,17,2009
1660,San Jose,USA,37.337756,-121.894350,DeciZium,web,12,2006
1661,Hamburg,DEU,53.554390,10.017753,jogmap media,web,3,2006
1662,Guelph,CAN,43.544964,-80.249862,MFE Interactive,web,5,2007
1663,London,GBR,51.517356,-0.103774,Testplant,software,50,2008
1664,Boulder,USA,40.023005,-105.253284,Testplant,software,50,2008
1665,Bear,USA,39.612223,-75.696706,FacebookLicious!,games_video,30,2007
1666,Chicago,USA,41.663359,-87.625905,Hiremac,software,9,2007
1667,Aliso Viejo,USA,33.564557,-117.735509,Tagito,web,4,2008
1668,Los Angeles,USA,34.013715,-118.466060,Culture Jam,web,15,2008
1669,Sydney,AUS,-33.868898,151.202966,Novera,software,10,2006
1670,Berlin,DEU,52.494307,13.434474,Sauspiel,games_video,8,2007
1671,Paris,FRA,53.332814,-6.249378,ftopia,software,7,2009
1672,Cambridge,USA,42.367287,-71.081447,Tiverias Apps,software,20,2009
1673,Surbiton,GBR,51.393654,-0.306263,AgileJ Limited,software,3,2006
1674,Beverly Hills,USA,34.069891,-118.405325,HOTForms123,web,2,2009
1675,New York,USA,40.746497,-74.009447,Film Annex,games_video,5,2006
1676,New Haven,USA,41.327918,-73.243552,Continuity Engine,software,11,2008
1677,Vancouver,CAN,49.284394,-123.109262,FundRazr,social,6,2008
1678,San Francisco,USA,37.784174,-122.449408,DJ Nitrogen,games_video,8,2007
1679,Herlev,DNK,55.752525,12.393304,Meeho!,software,5,2007
1680,New York,USA,40.726160,-74.006023,ALOT,software,50,2007
1681,New York City,USA,40.756054,-73.986951,Conversition,web,10,2008
1682,Astoria,USA,40.759795,-73.916127,Fictionaut,games_video,2,2008
1683,Houston,USA,29.735462,-95.413243,Fictionaut,games_video,2,2008
1684,PARIS,FRA,48.869995,2.340695,PubliAtis,software,10,2006
1685,Vancouver,CAN,49.282455,-123.109217,Tiny Speck,games_video,45,2009
1686,Lisbon,PRT,38.752367,-9.146221,My TV Shows,games_video,2,2007

In [23]:
data.tail()

Empty DataFrame
Columns: []
Index: []